# 药物响应预测系统配置文件

# 数据相关配置
data:
  # 数据文件路径
  ic50_path: 'src/data/filtered_ic50_data2.csv'
  drug_encoded_path: 'src/data/one_hot_drugs.csv'
  protein_path: 'src/data/DAE_features_dim100.csv'

  # 数据处理参数
  test_size: 0.2          # 测试集比例（用于非交叉验证模式）
  validation_size: 0.25   # 验证集比例（用于非交叉验证模式）
  seed: 42                # 随机种子，确保结果可复现

  # 交叉验证配置
  cross_validation:
    enabled: true          # 启用交叉验证
    n_splits: 5            # 五折交叉验证
    shuffle: true          # 打乱数据
    stratify_by: "drug_name"  # 分层抽样依据，可选："drug_name", "cell_line", null (不分层)
    random_state: 42  # 确保交叉验证分割可重复性

# 模型相关配置
model:
  type: "mlp"              # 模型类型: mlp, dnn, etc.
  hidden_dims: [128, 96, 64, 32] # 隐藏层神经元数量
  dropout_rate: 0.0        # Dropout比例
  activation: "relu"       # 激活函数: relu, tanh, sigmoid, etc.

# 训练相关配置
training:
  batch_size: 64           # 批次大小
  learning_rate: 0.001     # 学习率
  weight_decay: 0.0001     # 权重衰减（L2正则化）
  num_epochs: 100          # 最大训练轮次
  early_stopping_patience: 10  # 早停的耐心值
  use_cuda: true           # 是否使用GPU
  logging_steps: 5         # 每多少个epoch记录一次日志
  optimizer: "adam"        # 优化器: adam, sgd, rmsprop, etc.
  
scheduler:
  enabled: true          # 是否使用学习率调度器
  type: "plateau"        # 调度器类型: plateau, step, cosine, etc.
  patience: 5           # ReduceLROnPlateau的耐心值
  factor: 0.5            # 学习率衰减因子
  min_lr: 0.00001        # 最小学习率

# 评估相关配置
evaluation:
  metrics: ["mae", "rmse", "r2", "pearson", "spearman", "ci", "mape"]

# 添加顶级可视化配置（这是关键修改）
visualization:
  enabled: true
  save_plots: true
  show_plots: false      # 是否显示图表（通常在服务器上设为false）

# 输出相关配置
output:
  model_dir: "models"      # 模型保存目录
  results_dir: "results"   # 结果保存目录
  log_dir: "logs"          # 日志保存目录
  export_predictions: true # 是否导出预测结果
  experiment_name: "drug_response_experiment"